name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This runs it automatically every day at midnight!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          filter-duplicate-solutions: true
